background {
    monitor =
    color = rgba(20,20,20,1.0)
    blur_size = 5
    blur_passes = 2
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    fade_on_empty = false
    placeholder_text = Password...
}

label {
    monitor =
    text = Locked
    font_size = 40
    position = 0, 80
}
