# Window behavior
location = center
anchor = center
width = 350
height = 120
layer = overlay

# Layout
show = dmenu
columns = 2
lines = 1
prompt =

# Behavior
allow_markup = true
hide_scroll = true
insensitive = true
no_actions = true
exit_on_deselect = true
hide_search = true

# Launch behavior
normal_window = false